### ISSUE TITLE
Can't build react-motion with node 0.12.0 

### ISSUE THREAD

**Issue by daedelus-j** [chenglou/react-motion#228]
```
> react-motion@0.3.1 prerelease /Users/amadeus/projects/apps/other/react-motion
> babel src --out-dir lib && babel native/non-compiled.js > native/index.js && webpack --config webpack.prod.config.js

/usr/local/bin/babel: line 3: syntax error near unexpected token `"The CLI has been moved into the package `babel-cli`."'
/usr/local/bin/babel: line 3: `console.error("The CLI has been moved into the package `babel-cli`.");'

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prerelease"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! react-motion@0.3.1 prerelease: `babel src --out-dir lib && babel native/non-compiled.js > native/index.js && webpack --config webpack.prod.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the react-motion@0.3.1 prerelease script 'babel src --out-dir lib && babel native/non-compiled.js > native/index.js && webpack --config webpack.prod.config.js'.
npm ERR! This is most likely a problem with the react-motion package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src --out-dir lib && babel native/non-compiled.js > native/index.js && webpack --config webpack.prod.config.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-motion
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/amadeus/projects/apps/other/react-motion/npm-debug.log
```

FULL STACKTRACE

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'prerelease' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose run-script [ 'prerelease' ]
5 info prerelease react-motion@0.3.1
6 verbose unsafe-perm in lifecycle true
7 info react-motion@0.3.1 Failed to exec prerelease script
8 verbose stack Error: react-motion@0.3.1 prerelease: `babel src --out-dir lib && babel native/non-compiled.js > native/index.js && webpack --config webpack.prod.config.js`
8 verbose stack Exit status 2
8 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
8 verbose stack     at EventEmitter.emit (events.js:110:17)
8 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
8 verbose stack     at ChildProcess.emit (events.js:110:17)
8 verbose stack     at maybeClose (child_process.js:1008:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
9 verbose pkgid react-motion@0.3.1
10 verbose cwd /Users/amadeus/projects/apps/other/react-motion
11 error Darwin 14.5.0
12 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prerelease"
13 error node v0.12.0
14 error npm  v2.5.1
15 error code ELIFECYCLE
16 error react-motion@0.3.1 prerelease: `babel src --out-dir lib && babel native/non-compiled.js > native/index.js && webpack --config webpack.prod.config.js`
16 error Exit status 2
17 error Failed at the react-motion@0.3.1 prerelease script 'babel src --out-dir lib && babel native/non-compiled.js > native/index.js && webpack --config webpack.prod.config.js'.
17 error This is most likely a problem with the react-motion package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     babel src --out-dir lib && babel native/non-compiled.js > native/index.js && webpack --config webpack.prod.config.js
17 error You can get their info via:
17 error     npm owner ls react-motion
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]
```

**Comment by daedelus-j** [comment]
Nvm this was my own environment issue
