### ISSUE TITLE
npm run dev fails

### ISSUE THREAD

**Issue by luisrudge** [chenglou/react-motion#328]
Windows 10, build 14342

```
λ npm -v
3.3.12

λ node -v
v5.4.0

λ npm run dev

> spectacle-editor@0.0.1 dev c:\git\oss\spectacle-editor
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

[1]
[1] > spectacle-editor@0.0.1 start-hot c:\git\oss\spectacle-editor
[1] > cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development
[1]
[0]
[0] > spectacle-editor@0.0.1 hot-server c:\git\oss\spectacle-editor
[0] > node -r babel-register server.js
[0]
[1] fs.js:584
[1]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
[1]                  ^
[1]
[1] Error: ENOENT: no such file or directory, open 'c:\git\oss\spectacle-editor\node_modules\electron-prebuilt\path.txt'
[1]     at Error (native)
[1]     at Object.fs.openSync (fs.js:584:18)
[1]     at Object.fs.readFileSync (fs.js:431:33)
[1]     at Object.<anonymous> (c:\git\oss\spectacle-editor\node_modules\electron-prebuilt\index.js:4:42)
[1]     at Module._compile (module.js:398:26)
[1]     at Object.Module._extensions..js (module.js:405:10)
[1]     at Module.load (module.js:344:32)
[1]     at Function.Module._load (module.js:301:12)
[1]     at Module.require (module.js:354:17)
[1]     at require (internal/module.js:12:17)
[1]
[1] npm
[1]  ERR! Windows_NT 10.0.14342
[1] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "c:\\git\\oss\\spectacle-editor\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-hot"
[1] npm ERR! node v5.4.0
[1] npm ERR! npm  v3.9.2
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! spectacle-editor@0.0.1 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the spectacle-editor@0.0.1 start-hot script 'cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the spectacle-editor package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs spectacle-editor
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls spectacle-editor
[1] npm ERR!
[1]  There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     c:\git\oss\spectacle-editor\npm-debug.log
[1] npm run start-hot exited with code 1
--> Sending SIGTERM to other processes..
[0] events.js:141
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: listen EADDRINUSE 127.0.0.1:3000
[0]     at Object.exports._errnoException (util.js:856:11)
[0]     at exports._exceptionWithHostPort (util.js:879:20)
[0]     at Server._listen2 (net.js:1237:14)
[0]     at listen (net.js:1273:10)
[0]     at net.js:1382:9
[0]     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
[0]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
[0]
[0] npm
[0]  ERR! Windows_NT 10.0.14342
[0] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "c:\\git\\oss\\spectacle-editor\\node_modules\\npm\\bin\\npm-cli.js" "run" "hot-server"
[0] npm
[0]  ERR! node v5.4.0
[0] npm ERR! npm  v3.9.2
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! spectacle-editor@0.0.1 hot-server: `node -r babel-register server.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the spectacle-editor@0.0.1 hot-server script 'node -r babel-register server.js'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the spectacle-editor package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     node -r babel-register server.js
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs spectacle-editor
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls spectacle-editor
[0] npm ERR! There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     c:\git\oss\spectacle-editor\npm-debug.log
[0] npm run hot-server exited with code null

npm ERR! Windows_NT 10.0.14342
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! spectacle-editor@0.0.1 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spectacle-editor@0.0.1 dev script 'concurrently --kill-others "npm run hot-server" "npm run start-hot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spectacle-editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently --kill-others "npm run hot-server" "npm run start-hot"
npm ERR! You can get their info via:
npm ERR!     npm owner ls spectacle-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\git\oss\spectacle-editor\npm-debug.log
```

**Comment by nkbt** [comment]
Are you trying to use Bash under Windows? If yes, I doubt it works yet =)

**Comment by nkbt** [comment]
Ah sorry, checked the log better, seen paths with `\\`, so not. I'll have a look then.

**Comment by luisrudge** [comment]
OH NOESSSSSSSSSSSSS! I had the wrong github tab opened. I'm **SO SORRY**. This error was from another project, who was linking this repo on their readme. I'm very sorry I wasted your time.

**Comment by nkbt** [comment]
Hah, no worries, @luisrudge!
That's fine =)
